# ==============================================================================
# E-commerce Interactive Sales Dashboard Project
# Week 6 Internship Task - Complete Code-Wise Graph Pipeline
# ==============================================================================

import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# 1. SETUP DIRECTORIES FOR ASSET RETENTION
os.makedirs('visualizations', exist_ok=True)
print("--- Workspace Environment Configured ---")

# 2. DATA ACQUISITION & INTEGRITY CLEANING
try:
    df = pd.read_csv('data/sales_data.csv')
    print("[SUCCESS] Source dataset loaded smoothly.")
    
    # Dynamic Column Mapping: Map 'Product' to 'Category' if needed
    if 'Product' in df.columns and 'Category' not in df.columns:
        df['Category'] = df['Product']
        
except FileNotFoundError:
    print("[WARNING] Target file not detected. Constructing mock simulation framework...")
    data_mock = {
        'Date': pd.date_range(start='2024-01-01', periods=100, freq='D'),
        'Category': ['Laptop', 'Tablet', 'Phone', 'Headphones', 'Monitor'] * 20,
        'Price': [1200, 450, 800, 150, 300] * 20,
        'Quantity': [1, 2, 1, 4, 2] * 20,
        'Region': ['North', 'South', 'East', 'West', 'North'] * 20
    }
    df = pd.DataFrame(data_mock)
    df['Total_Sales'] = df['Price'] * df['Quantity']

df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df['Date'] = pd.to_datetime(df['Date'])

# Ensure 'Total_Sales' calculation column exists securely
if 'Total_Sales' not in df.columns:
    df['Total_Sales'] = df['Quantity'] * df['Price']

# 3. INDIVIDUAL GRAPH PIPELINES (SEABORN & MATPLOTLIB)
sns.set_theme(style="whitegrid")

# Graph 1: Bar Chart – Product Sales
plt.figure(figsize=(8, 5))
prod_sales_static = df.groupby('Category')['Total_Sales'].sum().sort_values(ascending=False).reset_index()
sns.barplot(x='Category', y='Total_Sales', data=prod_sales_static, palette='Blues_r', hue='Category', legend=False)
plt.title('Total Sales Generated by Product Category', fontsize=12, fontweight='bold')
plt.ylabel('Total Sales ($)')
plt.tight_layout()
plt.savefig('visualizations/1_product_sales_bar.png')
plt.close()

# Graph 2: Line Chart – Monthly Sales Trend
plt.figure(figsize=(8, 5))
monthly_sales = df.set_index('Date').resample('ME')['Total_Sales'].sum().reset_index()
plt.plot(monthly_sales['Date'].astype(str), monthly_sales['Total_Sales'], marker='o', color='#2ca02c', linewidth=2)
plt.title('Monthly Sales Trend (Revenue Over Time)', fontsize=12, fontweight='bold')
plt.xlabel('Month')
plt.ylabel('Total Revenue ($)')
plt.xticks(rotation=30)
plt.tight_layout()
plt.savefig('visualizations/2_monthly_sales_trend.png')
plt.close()

# Graph 3: Box Plot – Sales Distribution
plt.figure(figsize=(8, 5))
sns.boxplot(x='Category', y='Total_Sales', data=df, palette='Set2', hue='Category', legend=False)
plt.title('Sales Value Distribution & Spread by Category', fontsize=12, fontweight='bold')
plt.ylabel('Transaction Value ($)')
plt.tight_layout()
plt.savefig('visualizations/3_sales_distribution_box.png')
plt.close()

# Graph 4: Violin Plot – Sales Density
plt.figure(figsize=(8, 5))
sns.violinplot(x='Region', y='Total_Sales', data=df, palette='Pastel1', hue='Region', legend=False)
plt.title('Sales Density Profile Across Operating Regions', fontsize=12, fontweight='bold')
plt.ylabel('Transaction Distribution Density')
plt.tight_layout()
plt.savefig('visualizations/4_sales_density_violin.png')
plt.close()

# Graph 5: Correlation Heatmap
plt.figure(figsize=(6, 5))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5, square=True)
plt.title('Numerical Feature Inter-Relationships', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig('visualizations/5_correlation_heatmap.png')
plt.close()


# 4. COMPILING THE COMBINED SUMMARY STATIC DASHBOARD (2x2 GRID)
fig, axes = plt.subplots(2, 2, figsize=(15, 12))
fig.suptitle('Executive Sales Performance Dashboard (Static Overview)', fontsize=18, fontweight='bold')

# Top Left: Category Sales Volume Spread
sns.boxplot(ax=axes[0, 0], x='Category', y='Total_Sales', data=df, palette='Set2', hue='Category', legend=False)
axes[0, 0].set_title('Category Transaction Ranges (Box Plot)')

# Top Right: Regional Concentration
sns.violinplot(ax=axes[0, 1], x='Region', y='Total_Sales', data=df, palette='Pastel1', hue='Region', legend=False)
axes[0, 1].set_title('Regional Sales Density Variance (Violin Plot)')

# Bottom Left: Statistical Feature Dependency Matrix
sns.heatmap(ax=axes[1, 0], data=df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt=".2f", square=False)
axes[1, 0].set_title('Statistical Interdependencies (Heatmap)')

# Bottom Right: Timeline Revenue Tracking
axes[1, 1].plot(monthly_sales['Date'].astype(str), monthly_sales['Total_Sales'], marker='s', color='crimson', linewidth=2)
axes[1, 1].set_title('Monthly Revenue Velocity (Line Chart)')
axes[1, 1].tick_params(axis='x', rotation=30)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.savefig('visualizations/static_summary_dashboard.png')
plt.close()
print("[SUCCESS] Static summary dashboard multi-grid drawn successfully.")


# 5. GRAPH 6: COMPILING COMPLETELY INTERACTIVE PLOTLY DASHBOARD
interactive_fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        'Product Sales Comparison (Bar Chart)', 
        'Monthly Sales Trends (Line Chart)', 
        'Sales Value Distribution (Box Plot)', 
        'Transaction Volume Mix (Scatter Map)'
    ),
    specs=[[{"type": "bar"}, {"type": "scatter"}], [{"type": "box"}, {"type": "scatter"}]]
)

# Interactive Component A: Product Sales Performance
prod_sales_plotly = df.groupby('Category')['Total_Sales'].sum().reset_index()
interactive_fig.add_trace(
    go.Bar(
        x=prod_sales_plotly['Category'], 
        y=prod_sales_plotly['Total_Sales'], 
        name='Product Net Value', 
        marker_color='royalblue',
        hovertemplate="Category: %{x}<br>Net Total: $%{y:,.2f}<extra></extra>"
    ),
    row=1, col=1
)

# Interactive Component B: Monthly Revenue Progress Tracker
interactive_fig.add_trace(
    go.Scatter(
        x=monthly_sales['Date'].astype(str), 
        y=monthly_sales['Total_Sales'], 
        mode='lines+markers', 
        name='Monthly Performance', 
        line=dict(color='green', width=3),
        hovertemplate="Period: %{x}<br>Revenue: $%{y:,.2f}<extra></extra>"
    ),
    row=1, col=2
)

# Interactive Component C: Categorical Price Profiles
interactive_fig.add_trace(
    go.Box(
        y=df['Total_Sales'], 
        x=df['Category'], 
        name='Distribution Properties', 
        marker_color='darkorange'
    ),
    row=2, col=1
)

# Interactive Component D: Feature Distribution Cluster Mapping
interactive_fig.add_trace(
    go.Scatter(
        x=df['Price'], 
        y=df['Total_Sales'], 
        mode='markers', 
        marker=dict(color=df['Quantity'], colorscale='Viridis', showscale=True), 
        name='Individual Invoices',
        hovertemplate="Unit Price: $%{x}<br>Total Line Sales: $%{y}<extra></extra>"
    ),
    row=2, col=2
)

# Applying Configuration Themes, Window Scale Controls, and Filtering Parameters
interactive_fig.update_layout(
    title_text="E-Commerce Interactive Performance Dashboard (Week 6 Mastering Workspace)",
    height=950,
    showlegend=False,
    template='plotly_white'
)

# Export complete layout setup into clean HTML distribution wrapper
interactive_fig.write_html('visualizations/interactive_sales_dashboard.html')
print("[SUCCESS] Graph 6: Interactive Plotly HTML file compiled cleanly.")
print("🏁 Execution complete! Open files inside your visualizations/ folder to view output assets.")
# ==============================================================================

# ==============================================================================
# TESTING EVIDENCE: TEST CASE 6 - INSIGHTS GENERATION
# ==============================================================================
print("\n--- Running Test Case 6: Insights Generation Verification ---")

try:
    # Calculate the business findings from the aggregated datasets
    top_category = prod_sales_plotly.loc[prod_sales_plotly['Total_Sales'].idxmax(), 'Category']
    top_category_sales = prod_sales_plotly['Total_Sales'].max()
    
    bottom_category = prod_sales_plotly.loc[prod_sales_plotly['Total_Sales'].idxmin(), 'Category']
    bottom_category_sales = prod_sales_plotly['Total_Sales'].min()
    
    total_net_revenue = df['Total_Sales'].sum()
    
    # Validation Check: Ensure data calculations are not null or broken
    assert pd.notna(top_category_sales), "Top category calculations failed."
    assert pd.notna(bottom_category_sales), "Bottom category calculations failed."
    assert total_net_revenue > 0, "Total portfolio revenue must be greater than zero."
    
    # Display the generated findings on the terminal
    print(f"   [FINDING] Top Performing Category: {top_category} (${top_category_sales:,.2f})")
    print(f"   [FINDING] Weakest Performing Category: {bottom_category} (${bottom_category_sales:,.2f})")
    print(f"   [FINDING] Aggregate Portfolio Revenue: ${total_net_revenue:,.2f}")
    
    print("\nTest Case 6 Result:")
    print("Expected Result: Business findings displayed correctly.")
    print("Status: PASS ✅")

except Exception as e:
    print(f"\nTest Case 6 Result:")
    print(f"Expected Result: Business findings displayed correctly.")
    print(f"Status: FAIL ❌ (Reason: {str(e)})")
# ==============================================================================